version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_backend
    environment:
      - DATABASE_URL="sqlite:///:memory:"
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
